astarte-platform/astarte_rpc

- .travis.yml
> .travis.yml: implement step 4 of issue #4

- CHANGELOG.md
- mix.exs
Update mix.exs and CHANGELOG.md.
Signed-off-by: Davide Bettio <davide.bettio@ispirata.com>
> Prepare 0.11.0-beta.2

- lib/astarte_rpc/protocol/proto/pairing/call.proto
- lib/astarte_rpc/protocol/proto/pairing/get_health.proto
- lib/astarte_rpc/protocol/proto/pairing/get_health_reply.proto
Enable health messages in pairing
> pairing: add health related proto messages

- CHANGELOG.md
initial_introspection change was not added to changelog.
> CHANGELOG.md: add missing entry

- CHANGELOG.md
- mix.exs
Update mix.exs version number and changelog file.
> Prepare 0.11.0

- mix.exs
Remove any default comment which is generated when creating a new Elixir project.
> Remove default comments

- CHANGELOG.md
- mix.exs
Update mix.exs version number and add 0.11.1 release date.
> Prepare 0.11.1 release

- CHANGELOG.md
- lib/astarte_rpc/protocol/proto/vmq_plugin/publish_reply.proto
Allow returning local and remote matches
Signed-off-by: Riccardo Binetti <riccardo.binetti@ispirata.com>
> Add publish_reply

- CHANGELOG.md
- mix.exs
Update version number and CHANGELOG.md.
> Prepare 1.0.0-alpha.1

- .github/workflows/build-workflow.yaml
- .tool-versions
- CHANGELOG.md
- mix.exs
Prepare v0.11.2 and update Elixir version to 1.8.2.
> Update version number to 0.11.2

- CHANGELOG.md
- mix.exs
> Bump version number to 0.11.3

- .github/workflows/build-workflow.yaml
- CHANGELOG.md
- mix.exs
Update CHANGELOG.md, bump mix.exs version and use setup-elixir 1.5.0.
> Prepare v0.11.4 release

- CHANGELOG.md
- mix.exs
> Prepare v1.0.0-beta.1

- mix.exs
- mix.lock
See [#569](https://github.com/astarte-platform/astarte/issues/569).
> Upgrade AMQP library to version 2.1

- CHANGELOG.md
- mix.exs
> Prepare 1.0.0-rc.0 release

- CHANGELOG.md
- mix.exs
> Prepare 1.0.1 release

- CHANGELOG.md
- mix.exs
- mix.lock
> Prepare 1.0.2 release

- .github/workflows/build-workflow.yaml
- .tool-versions
- CHANGELOG.md
Also, refresh some old tool versions in GH workflows.
> Bump Elixir and Erlang to 1.14.5 and 25.3.2, respectively 

- CHANGELOG.md
Forward-port changes from release-1.1 to master
> Forward-port changes from release-1.1 to master

- CHANGELOG.md
- mix.exs
Bump version and update CHANGELOG.md.
> Prepare 1.2.0 release

- CHANGELOG.md
- lib/astarte_rpc/protocol/proto/realm_management/call.pb.ex
- lib/astarte_rpc/protocol/proto/realm_management/call.proto
- lib/astarte_rpc/protocol/proto/realm_management/get_detailed_interfaces_list.pb.ex
- lib/astarte_rpc/protocol/proto/realm_management/get_detailed_interfaces_list.proto
- lib/astarte_rpc/protocol/proto/realm_management/get_detailed_interfaces_list_reply.pb.ex
- lib/astarte_rpc/protocol/proto/realm_management/get_detailed_interfaces_list_reply.proto
- lib/astarte_rpc/protocol/proto/realm_management/reply.pb.ex
- lib/astarte_rpc/protocol/proto/realm_management/reply.proto
Realm Management RPC: Allow to query all Realm interfaces with details
> Add interface details list to Realm Management RPC
